import { mkdir, rm, writeFile, copyFile } from 'node:fs/promises';
import path from 'node:path';
import { site, pages, evidence } from '../src/site-data.mjs';
const root = process.cwd();
const dist = path.join(root, 'dist');
const now = new Date().toISOString();
const esc = (s='') => String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const outRel = p => p === '/' ? '/index.html' : `${p}index.html`;
function schemaFor(p){
  const base = {'@context':'https://schema.org','@type':p.schema||'WebPage',name:p.h1,description:p.description,url:site.baseUrl.replace(/\/$/,'')+p.path};
  const graph=[base];
  if(p.faq?.length) graph.push({'@context':'https://schema.org','@type':'FAQPage',mainEntity:p.faq.map(([q,a])=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}}))});
  if(p.schema==='HowTo') graph.push({'@context':'https://schema.org','@type':'HowTo',name:p.h1,step:p.sections.map((s,i)=>({'@type':'HowToStep',position:i+1,name:s,text:s}))});
  return JSON.stringify(graph.length>1?{'@context':'https://schema.org','@graph':graph}:base);
}
function header(){return `<a class="skip" href="#main">Skip to content</a><header class="site-header"><nav class="nav" aria-label="Main navigation"><a class="brand" href="/"><span class="brand-chip">△</span><span>${site.brand}</span></a><div class="nav-links">${site.nav.map(([n,u])=>`<a href="${u}">${n}</a>`).join('')}<a class="button" href="/#check">Start Free Check</a></div><button class="hamburger" aria-label="Open menu" aria-expanded="false">☰</button><div id="mobile-menu" class="mobile-menu">${site.nav.map(([n,u])=>`<a href="${u}">${n}</a>`).join('')}<a class="button" href="/#check">Start Free Check</a><a href="/privacy/">Privacy</a><a href="/terms/">Terms</a></div></nav></header>`}
function footer(){return `<footer class="footer"><div class="footer-grid"><div><a class="brand" href="/"><span class="brand-chip">△</span><span>${site.brand}</span></a><p>${esc(site.disclaimers.footer)}</p><p>Preview/sample mode is active; automated detection remains disabled until provider validation and compliance review are complete.</p></div><div><strong>Links</strong><p><a href="/privacy/">Privacy</a> · <a href="/terms/">Terms</a> · <a href="/contact/">Contact</a></p><p><a href="/sitemap.xml">Sitemap</a> · <a href="/robots.txt">Robots</a></p></div></div></footer>`}
function tool(){return `<form id="check" class="tool-card" data-start-check><div class="tabs" role="tablist" aria-label="Choose input type"><button class="tab" type="button" role="tab" data-tab="upload" aria-selected="true">Upload a video clip</button><button class="tab" type="button" role="tab" data-tab="url" aria-selected="false">Paste a public video link</button></div><div data-panel="upload"><div class="drop"><strong>Preview upload panel</strong><p>Real media processing is not enabled yet. This launches a sample/manual checklist result only.</p><input type="file" aria-label="Choose video file" accept="video/*"></div></div><div data-panel="url" hidden><div class="field"><label for="video-url">Public video URL</label><input id="video-url" type="url" placeholder="https://www.youtube.com/watch?v=..." autocomplete="off"></div><p class="notice">${esc(site.disclaimers.publicLinks)}</p></div><div class="consent"><input id="consent" type="checkbox" name="consent"><label for="consent">${esc(site.disclaimers.consent)}</label></div><button class="button" type="submit">Start Free Preview</button><p class="notice">Current preview may show sample/manual checklist mode until automated detection is validated.</p><p class="notice error" role="alert"></p><p class="notice status" role="status"></p></form>`}
function evidenceBlock(){return `<div class="evidence">${evidence.map(([h,p,b])=>`<article class="evidence-item"><span class="pill">${esc(b)}</span><h3>${esc(h)}</h3><p>${esc(p)}</p></article>`).join('')}</div>`}
const googleAnalyticsId = 'G-1D2BC3CZ2M';
function analyticsHead(){return `<script async src="https://www.googletagmanager.com/gtag/js?id=${googleAnalyticsId}"></script><script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}gtag('js',new Date());gtag('config','${googleAnalyticsId}');</script>`}
function commonHead(p){const url=site.baseUrl.replace(/\/$/,'')+p.path;return `<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(p.title)}</title><meta name="description" content="${esc(p.description)}"><link rel="canonical" href="${url}"><meta name="robots" content="index,follow"><meta property="og:title" content="${esc(p.title)}"><meta property="og:description" content="${esc(p.description)}"><meta property="og:type" content="website"><meta property="og:url" content="${url}"><meta name="twitter:card" content="summary_large_image">${analyticsHead()}<link rel="stylesheet" href="/assets/styles.css"><script type="application/ld+json">${schemaFor(p)}</script>`}
function mainPage(p){
  const cards=p.sections.map(s=>`<article class="card"><h3>${esc(s)}</h3><p>Designed for cautious screening with clear labels, limitations, and no forensic or legal proof claims.</p></article>`).join('');
  const faq=p.faq?.length?`<section class="section light"><div class="wrap"><h2>Frequently asked questions</h2><div class="faq">${p.faq.map(([q,a])=>`<details><summary>${esc(q)}</summary><p>${esc(a)}</p></details>`).join('')}</div></div></section>`:'';
  return `<!doctype html><html lang="en"><head>${commonHead(p)}</head><body>${header()}<main id="main"><section class="hero"><div class="hero-grid"><div><span class="eyebrow">${esc(p.eyebrow)}</span><h1>${esc(p.h1)}</h1><p class="lead">${esc(p.intro)}</p><div class="cta-row"><a class="button" href="#check">${esc(p.cta)}</a><a class="ghost" href="/sample-report/">${esc(p.secondaryCta)}</a></div><div class="trust-row"><span>Free preview</span><span>No signup for basic checks</span><span>${esc(site.disclaimers.hero)}</span></div><p class="notice">${esc(site.disclaimers.sample)}</p></div>${tool()}</div></section><section class="section light"><div class="wrap"><h2>Evidence dashboard, not a verdict machine</h2><p>This interface follows the data contract: sample/manual mode never presents a real user-specific verdict, confidence score, or evidence. Provider inference remains disabled until a real provider/model, retention policy, deletion flow, and compliance review are confirmed.</p><div class="grid">${cards}</div></div></section><section class="section dark"><div class="wrap"><h2>Sample report structure</h2><p>${esc(site.disclaimers.result)}</p>${evidenceBlock()}</div></section><section class="section light"><div class="wrap"><h2>Free preview and early access</h2><div class="pricing"><article class="price-card featured"><span class="pill">Active preview</span><h3>Free Preview</h3><p>Sample report and manual checklist mode. No paid checkout and no real automated verdict.</p><a class="button" href="#check">Start Free Preview</a></article><article class="price-card"><span class="pill">Waitlist</span><h3>Early Access</h3><p>Join for updates when provider inference, limits, and privacy terms are confirmed.</p><a class="ghost" href="/contact/">Join Early Access</a></article><article class="price-card disabled"><span class="pill">Coming soon</span><h3>Pro / Agency</h3><p>Future paid plans require owner decisions for pricing, refunds, taxes, and credit rules.</p><a class="ghost" href="/contact/">Request updates</a></article></div></div></section>${faq}</main>${footer()}<script src="/assets/app.js" type="module"></script></body></html>`;
}
function legalPage(p){return `<!doctype html><html lang="en"><head>${commonHead(p)}</head><body class="legal-body">${header()}<main id="main" class="legal-main"><span class="eyebrow">${esc(p.eyebrow)}</span><h1>${esc(p.h1)}</h1><p class="lead" style="color:#425466">${esc(p.intro)}</p><p class="notice">${esc(site.disclaimers.hero)}</p><p class="notice">${esc(site.disclaimers.sample)}</p><div class="grid" style="grid-template-columns:1fr 1fr">${p.sections.map(s=>`<article class="card"><h2>${esc(s)}</h2><p>${esc(s==='Preview/sample mode'?site.disclaimers.sample:site.disclaimers.result)}</p></article>`).join('')}</div>${p.type==='contact'?`<form class="contact-box" data-contact><h2>Contact form preview</h2><div class="field"><label>Name or team</label><input type="text" required></div><div class="field"><label>Message</label><textarea rows="5" required></textarea></div><button class="button" type="submit">Submit Preview</button><p class="notice status" role="status"></p></form>`:''}</main>${footer()}<script src="/assets/app.js" type="module"></script></body></html>`}
await rm(dist,{recursive:true,force:true});
await mkdir(path.join(dist,'assets'),{recursive:true});
await copyFile(path.join(root,'src','styles.css'),path.join(dist,'assets','styles.css'));
await copyFile(path.join(root,'src','app.js'),path.join(dist,'assets','app.js'));
for(const p of pages){const out=path.join(dist,outRel(p.path));await mkdir(path.dirname(out),{recursive:true});await writeFile(out,(p.type==='legal'||p.type==='contact')?legalPage(p):mainPage(p));}
await writeFile(path.join(dist,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${pages.map(p=>`  <url><loc>${site.baseUrl.replace(/\/$/,'')}${p.path}</loc><lastmod>${now}</lastmod></url>`).join('\n')}\n</urlset>\n`);
await writeFile(path.join(dist,'robots.txt'),`User-agent: *\nAllow: /\nDisallow: /scan/\nDisallow: /api/\nSitemap: ${site.baseUrl.replace(/\/$/,'')}/sitemap.xml\n`);
await writeFile(path.join(dist,'_headers'),`/scan/*\n  X-Robots-Tag: noindex, nofollow\n/api/*\n  X-Robots-Tag: noindex, nofollow\n/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n`);
await writeFile(path.join(dist,'404.html'),`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="robots" content="noindex"><title>Page not found</title><link rel="stylesheet" href="/assets/styles.css"><body class="legal-body"><main class="legal-main"><h1>Page not found</h1><p>The requested page is unavailable.</p><a class="button" href="/">Return home</a></main></body></html>`);
console.log(`Built ${pages.length} pages to ${dist}`);
