export const site = {
  brand: 'AI Video Detector',
  baseUrl: 'https://detectvideo.vip',
  nav: [
    ['AI Video Detector', '/ai-video-detector/'],
    ['YouTube Detector', '/youtube-ai-video-detector/'],
    ['Deepfake Detector', '/deepfake-video-detector/'],
    ['Sample Report', '/sample-report/'],
    ['Contact', '/contact/']
  ],
  disclaimers: {
    hero: 'Educational signal, not forensic proof.',
    consent: 'I confirm that I have the right to upload or analyze this video or link, and I understand the result is a preliminary signal, not legal or forensic proof.',
    sample: 'Sample report only — this is demo content and not an analysis of your video.',
    result: 'This report is a preliminary AI/deepfake likelihood signal. It can be wrong, especially for compressed, edited, low-resolution, edited, or screen-recorded videos. Do not use it as the sole basis for legal, safety, employment, moderation, or other high-impact decisions.',
    publicLinks: 'Public-link checks depend on platform availability. We do not bypass login, paywall, DRM, private-account, or platform access restrictions. If a link cannot be processed, upload a file you have the right to analyze.',
    footer: 'Results are preliminary educational signals, not forensic, legal, or moderation proof. This site is independently operated and is not affiliated with similarly named AI video detector sites or any video platform.'
  }
};

export const sharedFaq = [
  ['Can this prove whether a video is AI-generated?', 'No. The current preview is an educational first-pass screening workflow. It shows sample/manual checklist mode unless a real detector provider is configured and compliance-reviewed.'],
  ['Can I paste a YouTube or social video link?', 'You can paste a public link for the preview flow, but public-link processing depends on platform availability and access restrictions. We do not bypass logins, paywalls, DRM, or private accounts.'],
  ['Do I need an account?', 'The planned MVP is a free preview without signup for basic checks. Future paid or authenticated features require owner confirmation.'],
  ['What should I do with an inconclusive result?', 'Treat it as a prompt for further review. Check the source, context, upload history, editing artifacts, and trusted reporting before making high-impact decisions.']
];

export const pages = [
  ['/', 'AI Video Detector for YouTube & Social Videos | AI Video Detector', 'Upload a clip or paste a public YouTube or social video link to screen for AI-generated or deepfake signals. Get a preliminary evidence-style report with clear limitations.', 'AI Video Detector for YouTube & Social Videos', 'Free preview · sample/manual mode', 'Start Free Check', 'View Sample Report', 'Upload a clip or paste a public video link to screen for AI-generated, deepfake, or manipulated video signals. The report is an educational first-pass review with visible limitations, not forensic or legal proof.', ['Evidence-style report preview','Upload or paste a public link','Clear limitations near every result','Manual checklist while automated detection is validated'], sharedFaq, 'WebApplication'],
  ['/ai-video-detector/', 'AI Video Detector Online — Free Preview for Uploaded Clips & Public Links', 'Use an AI video detector online to screen uploaded clips or public video links for AI-generated and manipulated video signals. Free preview with clear limitations.', 'AI Video Detector Online', 'Main SEO tool preview', 'Start Free Check', 'View Sample Report', 'Screen an uploaded video or public social link for preliminary AI-generated and manipulated video signals. Current launch mode is sample/manual checklist until provider inference is validated.', ['AI-generated video signals','Deepfake and manipulation cues','Upload/link workflow','No signup for basic preview'], sharedFaq, 'SoftwareApplication'],
  ['/youtube-ai-video-detector/', 'YouTube AI Video Detector — Check Public Links or Upload Clips', 'Paste a public YouTube link or upload a clip you have the right to analyze. Screen for AI/deepfake video signals with clear link limitations and no forensic claims.', 'YouTube AI Video Detector', 'Public link workflow', 'Check a YouTube Video', 'Upload a Clip Instead', 'Paste a public YouTube URL or upload a clip you have the right to analyze. If the tool cannot fetch a public link, use an authorized upload instead.', ['Public YouTube link caveats','Upload fallback','Platform access limitations','Unaffiliated educational screening'], [['Can this check every YouTube link?','No. Public-link checks depend on availability, region, platform access, and technical limits. Private, login-only, DRM, paywalled, or unavailable videos are not processed.'], ['Is this affiliated with YouTube?','No. This site is independently operated and is not affiliated with YouTube or Google.'], ...sharedFaq.slice(0,2)], 'HowTo'],
  ['/deepfake-video-detector/', 'Deepfake Video Detector Online — Preliminary Signal Check', 'Check uploaded clips or public video links for possible deepfake signals, including face, lip-sync, voice, and motion inconsistencies. Educational signal only.', 'Deepfake Video Detector Online', 'Face · voice · motion signals', 'Check for Deepfake Signals', 'View Sample Deepfake Report', 'Review possible deepfake cues such as facial artifacts, lip-sync mismatch, voice inconsistencies, temporal glitches, and compression caveats. A clean report does not prove authenticity.', ['Face and lip-sync cues','Voice/audio mismatch checks','Motion consistency notes','Clean result does not prove authenticity'], [['What deepfake signals are reviewed?','The sample/manual report explains face/lip-sync, audio/voice, temporal consistency, metadata, and compression caveats.'], ['Can a deepfake detector be wrong?','Yes. Low-resolution, compressed, edited, or screen-recorded clips can confuse automated and manual checks.'], ...sharedFaq.slice(0,2)], 'SoftwareApplication'],
  ['/ai-generated-video-detector/', 'AI Generated Video Detector — Check Uploaded Clips & Public Links', 'Screen a video for possible AI-generated signals with an evidence-style report and clear limitations. Free preview, sample report, and early access available.', 'AI Generated Video Detector', 'Generated-video screening preview', 'Upload a Video', 'Paste a Public Link', 'Use a cautious evidence-style workflow to screen for possible AI-generated video signals. Model-specific accuracy claims are not made until benchmark evidence and provider inference are confirmed.', ['Generated motion artifacts','Scene consistency notes','Metadata/context checklist','No unsupported model-specific claims'], sharedFaq, 'FAQPage'],
  ['/video-authenticity-checker/', 'Video Authenticity Checker — AI & Deepfake Signal Checklist', 'Learn how to check video authenticity with a preliminary AI/deepfake signal checklist, public-link/upload workflow, limitations, and next steps.', 'Video Authenticity Checker', 'Manual checklist + preview workflow', 'Check Video Authenticity', 'Use the Manual Checklist', 'Check whether a video deserves deeper review by combining source checks, upload/link review, visual signal categories, and limitation-aware next steps.', ['Source and context checks','Visual/audio signal checklist','Public-link limitations','When to escalate for expert review'], sharedFaq, 'HowTo'],
  ['/check-video-ai-or-not/', 'Check if a Video Is AI or Not — Free Preview Checklist', 'Start a simple preliminary check to see whether a video may show AI-generated or manipulated signals. Educational preview with sample/manual mode.', 'Check if a Video Is AI or Not', 'Simple language preview', 'Start a Video Check', 'See a Sample Report', 'Not sure if a video is real, edited, or AI-generated? Start with a simple preview checklist and sample evidence report. Do not treat this as proof.', ['Upload or paste a link','Read the sample/manual checklist','Understand why results can be inconclusive','Choose next review steps'], sharedFaq, 'FAQPage'],
  ['/sample-report/', 'Sample AI Video Detection Report — Evidence Fields & Limitations', 'Preview a sample AI video detection report structure, evidence categories, limitations, and next steps before uploading a clip or public video link.', 'Sample AI Video Detection Report', 'Demo report only', 'Try Your Own Video', 'Read Limitations', 'This page shows the report format and evidence fields using demo content only. It is not an analysis of a user-supplied video.', ['Sample/manual mode badge','Evidence categories','Limitations list','Recommended next steps'], [['Is this sample report based on my video?','No. It is demo content only and not an analysis of your video.'], ['Why show a sample report?','The sample explains what future evidence fields and limitations will look like before real provider inference is enabled.'], ...sharedFaq.slice(0,2)], 'Article'],
  ['/privacy/', 'Privacy Policy — AI Video Detector Preview', 'Privacy policy for the AI Video Detector preview, including upload rights, data handling placeholders, retention limits, and contact options.', 'Privacy Policy', 'Preview policy — owner confirmation required before production uploads', 'Contact', 'Read Terms', 'This preview does not enable production media processing. Before real uploads launch, retention, deletion, provider disclosure, and no-training terms must be confirmed.', ['Upload rights and consent','Preview/sample mode','Retention and deletion to be confirmed','Third-party provider disclosure required before launch'], [], 'WebPage', 'legal'],
  ['/terms/', 'Terms of Use — AI Video Detector Preview', 'Terms of use for the AI Video Detector preview, including educational-only limitations, prohibited uses, and no forensic/legal reliance.', 'Terms of Use', 'Educational preview terms', 'Contact', 'Read Privacy', 'The service is an educational preview and must not be used as sole proof for legal, safety, employment, moderation, or other high-impact decisions.', ['Educational use only','No forensic/legal proof','No prohibited/private uploads','Future paid terms require owner confirmation'], [], 'WebPage', 'legal'],
  ['/contact/', 'Contact — AI Video Detector Preview', 'Contact the operator about the AI Video Detector preview, deletion requests, public-link limitations, early access, and feedback.', 'Contact', 'Support and early access', 'Join Early Access', 'Read Privacy', 'Use the contact form preview for feedback, deletion questions, provider disclosure requests, or early-access interest while production email intake is being finalized.', ['Early access interest','Deletion or privacy questions','Bug/unsupported-link reports','Production email intake pending'], [], 'WebPage', 'contact']
].map(([path,title,description,h1,eyebrow,cta,secondaryCta,intro,sections,faq,schema,type]) => ({path,title,description,h1,eyebrow,cta,secondaryCta,intro,sections,faq,schema,type}));

export const evidence = [
  ['Visual artifact review', 'Demo only: inconsistent edges, reflections, and compression artifacts would be summarized here.', 'Sample'],
  ['Temporal consistency', 'Demo only: frame-to-frame motion or object continuity notes would appear here.', 'Sample'],
  ['Face and lip-sync', 'Manual checklist: compare mouth movement, voice timing, and face geometry across cuts.', 'Not run'],
  ['Public-link limitation', 'Some public links cannot be fetched due to platform, region, login, DRM, or availability restrictions.', 'Limitation']
];
